* DNS Updater

** SYNOPSIS
   =$ dnsup [-h|-s]=

** DESCRIPTION
   Update a host's A record when its external IPv4 address changes.  The update
   is performed using a DNS provider's API.  Gandi, GoDaddy, and Porkbun are
   supported.

#+BEGIN_EXAMPLE
   -h    Print this help message.
   -s    Be silent except upon error.
#+END_EXAMPLE

   A configuration file, typically named <domain>.<record>.conf (e.g.,
   home.example.com.conf), is read from /etc/dnsup/ or /usr/local/etc/dnsup/ for
   each A record to be updated.

   Configuration values

   Common:
#+BEGIN_SRC sh
  provider=<Gandi | GoDaddy | Porkbun>
  domain=<domain name>
  name=<Use @ or leave blank for zone root, otherwise subdomain without domain>
  ttl=<TTL in seconds, minimum of 600 for Porkbun>
#+END_SRC

  Gandi:
#+BEGIN_SRC sh
  pat=<Personal Access Token>>
#+END_SRC

  Godaddy:
#+BEGIN_SRC sh
  key=<API key>
  secret=<API key secret>
#+END_SRC

  Porkbun:
#+BEGIN_SRC sh
  apikey=<API key>
  secretapikey=<secret API key>
#+END_SRC

** API Keys

   To learn about the API keys and configuration values specific to each provider, visit these sites.

   Gandi: https://api.gandi.net/
   GoDaddy: https://developer.godaddy.com
   Porkbun: https://porkbun.com/account/api

** COMPATIBILITY
   dnsup is written in POSIX shell.  It requires curl with TLS support and a CA
   certificate store.

** EXAMPLE
~$ cat /etc/crontab~
#+BEGIN_SRC sh
PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
SHELL=/bin/sh

#minute	hour	mday	month	wday	who	command
*/5     *       *       *       *       dnsup    dnsup >> /var/log/dnsup.log 2>&1
@reboot                                 dnsup    dnsup >> /var/log/dnsup.log 2>&1
#+END_SRC

** AUTHOR
   Joseph Mingrone <jrm@ftfl.ca>

** LICENSE
   dnsup is released under a BSD 2-Clause License.
