* DNS Updater

** SYNOPSIS
   =$ dnsup [-h|-s]=

** DESCRIPTION
   Update a host's A record when its external IP address changes.  The update is
   performed using your DNS provider's API.

   Gandi's LiveDNS and GoDaddy's managed DNS service are supported.  For now,
   only IPv4 addresses can be updated.  I no longer have any domains registered
   with Godaddy, so it's been years since I tested with them.  Testers and
   patches are welcomed.
#+BEGIN_EXAMPLE
   -h    Print this help message.
   -s    Be silent except upon error.
#+END_EXAMPLE

   The following variables are read from =/usr/local/etc/dnsup.conf=.

#+BEGIN_SRC sh
  provider=    Gandi | GoDaddy
  key=         <Gandi API key | GoDaddy API key>
  domain=      <domain to update; defaults to host domain; may be comma-separated list>
  record=      <DNS record to update; defaults to @>
  ttl=         <TTL in seconds; defaults to 10800>
#+END_SRC

   An additional value required when the provider is Godaddy.

#+BEGIN_SRC sh
  secret=       <API key secret>
#+END_SRC

** API Documentation

   Gandi: https://api.gandi.net/
   
   GoDaddy: https://developer.godaddy.com

** COMPATIBILITY
   dnsup is written in POSIX shell.  It requires curl with TLS support and a CA
   certificate store such as the ca_root_nss package on FreeBSD or the
   ca-certificates package on Debian based distributions and Arch.

** EXAMPLE
~$ cat /etc/crontab~
#+BEGIN_SRC sh
PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
SHELL=/bin/sh

#minute	hour	mday	month	wday	who	command
*/5     *       *       *       *       dnsup    dnsup >> /var/log/dnsup.log 2>&1
@reboot                                 dnsup    dnsup >> /var/log/dnsup.log 2>&1
#+END_SRC

** AUTHOR
   Joseph Mingrone <jrm@ftfl.ca>

** LICENSE
   dnsup is released under a BSD 2-Clause License.