* DNS Updater

** SYNOPSIS
   =$ dnsup [-h|-s]=

** DESCRIPTION
   Update a host's A record when its external IP address changes.  The update is
   performed using your DNS provider's API.

   Gandi's LiveDNS and GoDaddy's managed DNS service are supported.  For now,
   Only IPv4 addresses can be updated.  I no longer have any domains registered
   with Godaddy, so it has been years since I tesed with them.  Patches are
   welcomed.
#+BEGIN_EXAMPLE
   -h    Print this help message.
   -s    Be silent except upon error.
#+END_EXAMPLE

   The following variables are read from =/usr/local/etc/dnsup.conf=.

   Values required for both Gandi and Godaddy

#+BEGIN_SRC sh
  provider=<Gandi | GoDaddy>
  key=<Gandi API key | GoDaddy API key>
  ttl=<TTL in seconds>
#+END_SRC

   Additional values required when provider is Gandi

#+BEGIN_SRC sh
  domain=
  host=
  record=
#+END_SRC

   Additional value required when provider is Godaddy

#+BEGIN_SRC sh
  secret=<API key secret>
#+END_SRC

** API Keys

   Gandi: https://api.gandi.net/
   GoDaddy: https://developer.godaddy.com

** COMPATIBILITY
   dnsup is written in POSIX shell.  It requires curl with TLS support and a CA
   certificate store.

** EXAMPLE
~$ cat /etc/crontab~
#+BEGIN_SRC sh
PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
SHELL=/bin/sh

#minute	hour	mday	month	wday	who	command
*/5     *       *       *       *       dnsup    dnsup >> /var/log/dnsup.log 2>&1
@reboot                                 dnsup    dnsup >> /var/log/dnsup.log 2>&1
#+END_SRC

** AUTHOR
   Joseph Mingrone <jrm@ftfl.ca>

** LICENSE
   dnsup is released under a BSD 2-Clause License.  Refer to the header of each
   source file for details.